[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo-console = "0.3.0"
yew = {version="0.21.0", features=["csr"]}
yew-router = "0.18.0"

[[bin]]
name = "frontend"
path = "src/main.rs"


[lib]
crate-type = ["lib"]
