[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-rt = "2.10.0"
actix-web = "4.9.0"
dotenv = "0.15.0"
serde = "1.0.216"
serde_json = "1.0.133"
sqlx = { version = "0.8.2", features = [ "postgres", "runtime-tokio" ] }
